# Target                 Title     BG        Text      Indicator  Border
#client.focused           #89b4fa   #1e1e2e   #cdd6f4   #f5c2e7    #89b4fa
#client.focused_inactive  #6c7086   #181825   #6c7086   #181825    #6c7086
#client.unfocused         #6c7086   #181825   #6c7086   #181825    #6c7086
#client.urgent            #f38ba8   #f38ba8   #1e1e2e   #f38ba8    #f38ba8

# Target                 Title     BG       Text     Indicator  Border
client.focused           #99bc80   #242526  #f1e9d2  #99bc80    #99bc80
client.focused_inactive  #575855   #353634  #cfc8b0  #575855    #575855
client.unfocused         #353634   #242526  #888888  #242526    #353634
client.urgent            #e75a7c   #e75a7c  #f1e9d2  #e75a7c    #e75a7c
