set $gnome-schema org.gnome.desktop.interface
exec_always {
    gsettings set $gnome-schema gtk-theme 'Everforest-Dark'
    gsettings set $gnome-schema icon-theme 'Everforest-Dark'
    gsettings set $gnome-schema color-scheme 'Everforest-Dark'
}
